name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish for Windows
      run: dotnet publish -r win10-x64 --no-self-contained

    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: sync-to-onedrive-win10-x64 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/sync-to-onedrive/sync-to-onedrive/bin/Debug/net6.0/win10-x64/publish/
